### ISSUE TITLE
Negative Binomial Observed Distribution

### ISSUE THREAD

**Issue by juanitorduz** [probml/sts-jax#12]
Hi! It would be nice to have the ability to model negative binomial observations. What do you think is the effort to adapt the current approach for Poisson observations?

**Comment by xinglong-li** [comment]
As you might have noticed, the inference algorithm of sts-jax is taken from dynamax, since sts is just a state space model with a structured transition matrix and emission matrix. So I think if we are to support the negative binomial distribution in sts models, a better path is to add the negative binomial distribution to the state space model in dynamax.
